---

- name: Create responder cloudformation IGW stack
  cloudformation:
    aws_access_key: "{{ cloud_vpn_responder_aws_access_key  }}"
    aws_secret_key: "{{ cloud_vpn_responder_aws_secret_key  }}"
    security_token: "{{ cloud_vpn_responder_aws_security_token | default(omit) }}"
    region: "{{ cloud_vpn_responder_aws_region }}"
    stack_name: "{{ cloud_vpn_name }}-responder-igw-stack"
    template_body: "{{ lookup('template', 'templates/cloud_vpn/provisioners/aws_igw/responder/provision.j2') }}"
