---

- name: Create initiator cloudformation IGW stack
  cloudformation:
    aws_access_key: "{{ cloud_vpn_initiator_aws_access_key  }}"
    aws_secret_key: "{{ cloud_vpn_initiator_aws_secret_key  }}"
    security_token: "{{ cloud_vpn_initiator_aws_security_token | default(omit) }}"
    region: "{{ cloud_vpn_initiator_aws_region }}"
    stack_name: "{{ cloud_vpn_name }}-initiator-igw-stack"
    template_body: "{{ lookup('template', 'templates/cloud_vpn/provisioners/aws_igw/initiator/provision.j2') }}"

- name: Get VPC facts
  ec2_vpc_net_facts:
    aws_access_key: "{{ cloud_vpn_initiator_aws_access_key }}"
    aws_secret_key: "{{ cloud_vpn_initiator_aws_secret_key }}"
    security_token: "{{ cloud_vpn_initiator_aws_security_token | default(omit) }}"
    region: "{{ cloud_vpn_initiator_aws_region }}"
    filters:
      tag:Name: "{{ cloud_vpn_name }}-initiator-vpc"
  register: out

- name: Set initiator VPC id
  set_fact:
    cloud_vpn_initiator_vpc_id: "{{ out['vpcs'][0]['vpc_id'] }}"

- name: Get route table facts
  ec2_vpc_route_table_facts:
    aws_access_key: "{{ cloud_vpn_initiator_aws_access_key }}"
    aws_secret_key: "{{ cloud_vpn_initiator_aws_secret_key }}"
    security_token: "{{ cloud_vpn_initiator_aws_security_token | default(omit) }}"
    region: "{{ cloud_vpn_initiator_aws_region }}"
    filters:
      vpc-id: "{{ cloud_vpn_initiator_vpc_id }}"
  register: out

- name: Set initiator route table ID
  set_fact:
    cloud_vpn_initiator_route_table_id: "{{ out['route_tables'][0]['id'] }}"
