---

- name: Create initiator keypair
  ec2_key:
    aws_access_key: "{{ cloud_vpn_initiator_aws_access_key  }}"
    aws_secret_key: "{{ cloud_vpn_initiator_aws_secret_key  }}"
    security_token: "{{ cloud_vpn_initiator_aws_security_token | default(omit) }}"
    region: "{{ cloud_vpn_initiator_aws_region }}"
    name: "{{ cloud_vpn_initiator_key_name }}"
    key_material: "{{ lookup('pipe', 'ssh-keygen -y -f ' + cloud_vpn_initiator_ssh_private_key_file) }}"
