---

- name: Include aws_vpc deprovisioner tasks if needed
  include_tasks: "{{ role_path }}/tasks/cloud_vpn/provisioners/aws_vpc/responder/deprovision.yaml"
  when: cloud_vpn_responder_vpc is not defined

- name: Include aws_instance deprovisioner tasks
  include_tasks: "{{ role_path }}/tasks/cloud_vpn/provisioners/aws_instance/responder/deprovision.yaml"
